"""added embedding column

Revision ID: 27abe6aacd99
Revises: 00b599e5ab56
Create Date: 2026-07-20 13:49:09.554193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '27abe6aacd99'
down_revision: Union[str, Sequence[str], None] = '00b599e5ab56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunk', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunk', 'embedding')
    # ### end Alembic commands ###
