"""added hash field for normalized text

Revision ID: 527ef7667b4e
Revises: c22fe4b0597b
Create Date: 2026-05-06 15:36:53.366224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '527ef7667b4e'
down_revision: Union[str, Sequence[str], None] = 'c22fe4b0597b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_content', sa.Column('content_hash', sa.Text(), nullable=False))
    op.create_unique_constraint(op.f('document_content_document_id_key'), 'document_content', ['document_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('document_content_document_id_key'), 'document_content', type_='unique')
    op.drop_column('document_content', 'content_hash')
    # ### end Alembic commands ###
