"""added table document_chunk

Revision ID: 5a330beaa413
Revises: e1050903cbde
Create Date: 2026-05-06 17:11:35.028830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a330beaa413'
down_revision: Union[str, Sequence[str], None] = 'e1050903cbde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_document_chunk_content_id_chunk_hash'), 'document_chunk', type_='unique')
    op.create_unique_constraint('uq_document_chunk_content_id_chunk_index', 'document_chunk', ['content_id', 'chunk_index'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_chunk_content_id_chunk_index', 'document_chunk', type_='unique')
    op.create_unique_constraint(op.f('uq_document_chunk_content_id_chunk_hash'), 'document_chunk', ['content_id', 'chunk_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
