"""rename ingestion metrics

Revision ID: 8cc690ebdb7b
Revises: 9f4d7ba36f24
Create Date: 2026-04-29 17:14:13.143985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8cc690ebdb7b'
down_revision: Union[str, Sequence[str], None] = '9f4d7ba36f24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingestion_metric',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=True),
    sa.Column('stage', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ingest_metric')
    op.alter_column('document', 'status',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('document', 'source_url',
               existing_type=sa.TEXT(),
               nullable=True)
    op.add_column('job', sa.Column('type', sa.Text(), nullable=False))
    op.add_column('job', sa.Column('error_message', sa.Text(), nullable=True))
    op.alter_column('job', 'status',
               existing_type=sa.TEXT(),
               nullable=False)
    op.drop_column('job', 'error')
    op.drop_column('job', 'job_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('job_type', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('job', sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True))
    op.alter_column('job', 'status',
               existing_type=sa.TEXT(),
               nullable=True)
    op.drop_column('job', 'error_message')
    op.drop_column('job', 'type')
    op.alter_column('document', 'source_url',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('document', 'status',
               existing_type=sa.TEXT(),
               nullable=True)
    op.create_table('ingest_metric',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('stage', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('duration_ms', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], name=op.f('ingest_metric_document_id_fkey')),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name=op.f('ingest_metric_job_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('ingest_metric_pkey'))
    )
    op.drop_table('ingestion_metric')
    # ### end Alembic commands ###
