"""added table document_chunk

Revision ID: e1050903cbde
Revises: 527ef7667b4e
Create Date: 2026-05-06 17:06:14.359959

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1050903cbde'
down_revision: Union[str, Sequence[str], None] = '527ef7667b4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_chunk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('content_id', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.Text(), nullable=False),
    sa.Column('chunk_hash', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['document_content.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['document.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'chunk_index', name='uq_document_chunk_content_id_chunk_index')
    )
    op.drop_constraint(op.f('document_content_document_id_key'), 'document_content', type_='unique')
    op.create_unique_constraint('uq_document_content_document_id', 'document_content', ['document_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_document_content_document_id', 'document_content', type_='unique')
    op.create_unique_constraint(op.f('document_content_document_id_key'), 'document_content', ['document_id'], postgresql_nulls_not_distinct=False)
    op.drop_table('document_chunk')
    # ### end Alembic commands ###
